# Generated by Django 3.0.1 on 2020-01-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_id', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_name', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_email', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_tel', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_adress', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_bankacc', models.CharField(blank=True, max_length=120, null=True)),
                ('tea_bankname', models.CharField(blank=True, max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
