# Generated by Django 3.0.1 on 2020-01-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materialinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_id', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_shop', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_price', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_loc', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_inven', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toolinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(blank=True, max_length=120, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=120, null=True)),
                ('tool_shop', models.CharField(blank=True, max_length=120, null=True)),
                ('tool_price', models.CharField(blank=True, max_length=120, null=True)),
                ('tool_loc', models.CharField(blank=True, max_length=120, null=True)),
                ('tool_inven', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
