# Generated by Django 3.0.1 on 2020-01-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '__first__'),
        ('teacher', '__first__'),
        ('material', '__first__'),
        ('classstatd', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(blank=True, max_length=120, null=True)),
                ('class_date', models.DateField(blank=True, null=True)),
                ('class_cate', models.CharField(blank=True, max_length=120, null=True)),
                ('class_minicate', models.CharField(blank=True, max_length=120, null=True)),
                ('class_stat', models.CharField(blank=True, max_length=120, null=True)),
                ('class_stunum', models.CharField(blank=True, max_length=120, null=True)),
                ('class_time', models.CharField(blank=True, max_length=120, null=True)),
                ('class_place', models.CharField(blank=True, max_length=120, null=True)),
                ('class_count', models.CharField(blank=True, max_length=120, null=True)),
                ('class_sch', models.CharField(blank=True, max_length=120, null=True)),
                ('class_tea', models.CharField(blank=True, max_length=120, null=True)),
                ('memo', models.CharField(blank=True, max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('class_schkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Schoolinfo')),
                ('class_statkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classstatd.Classstatinfo')),
                ('class_teakey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='dyna_tool_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyna_tool_num', models.CharField(blank=True, max_length=120, null=True)),
                ('tool_re', models.BooleanField(default=False)),
                ('dyna_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.Classinfo')),
                ('tool_dyna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Toolinfo')),
            ],
        ),
        migrations.CreateModel(
            name='dyna_mat_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dyna_mat_num', models.CharField(blank=True, max_length=120, null=True)),
                ('mat_deliver_done', models.BooleanField(default=False)),
                ('mat_order_done', models.BooleanField(default=False)),
                ('dyna_mat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.Classinfo')),
                ('mat_dyna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Materialinfo')),
            ],
        ),
    ]
