# Generated by Django 3.0.1 on 2020-01-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='class_minicate',
        ),
    ]
