# Generated by Django 3.0.1 on 2020-01-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_remove_classinfo_class_minicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyna_mat_rel',
            name='mat_div_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dyna_mat_rel',
            name='mat_manu_done',
            field=models.BooleanField(default=False),
        ),
    ]
