# Generated by Django 3.0.1 on 2020-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20200105_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='class_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
