# Generated by Django 3.0.1 on 2020-01-07 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_auto_20200105_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_cal_meth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_deposit_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_doc_finestim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_doc_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_doc_preestim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_doc_tea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2020, 1, 7, 10, 50, 52, 505819, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
