# Generated by Django 3.0.1 on 2020-01-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_auto_20200107_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_re_done',
            field=models.BooleanField(default=False),
        ),
    ]
