# Generated by Django 3.0.1 on 2020-01-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('class', '0006_classinfo_class_re_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_mat_many',
            field=models.ManyToManyField(through='class.dyna_mat_rel', to='material.Materialinfo'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_tool_many',
            field=models.ManyToManyField(through='class.dyna_tool_rel', to='material.Toolinfo'),
        ),
    ]
