# Generated by Django 3.0.1 on 2020-01-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_auto_20200110_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='class_mat_many',
        ),
        migrations.RemoveField(
            model_name='classinfo',
            name='class_tool_many',
        ),
    ]
