# Generated by Django 3.0.1 on 2020-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0008_auto_20200110_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_cont_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_cont_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='class_cont_message',
            field=models.BooleanField(default=False),
        ),
    ]
