# Generated by Django 3.0.1 on 2020-01-10 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0009_auto_20200111_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dyna_mat_rel',
            name='dyna_mat_num',
            field=models.CharField(blank=True, default='수량을 입력해주세요', max_length=120, null=True),
        ),
    ]
