# Generated by Django 3.0.1 on 2020-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0010_auto_20200111_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='class_process',
            field=models.CharField(blank=True, default='진행X', max_length=120, null=True),
        ),
    ]
