# Generated by Django 3.0.1 on 2020-01-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classstatd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstatinfo',
            name='class_minicate',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
