# Generated by Django 3.0.1 on 2020-01-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classstatd', '0002_classstatinfo_class_minicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classstatinfo',
            name='recipe_mat',
        ),
        migrations.RemoveField(
            model_name='classstatinfo',
            name='recipe_tool',
        ),
    ]
