# Generated by Django 3.0.1 on 2020-01-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classstatd', '0003_auto_20200104_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat_tool_rel',
            old_name='stat_mat_num',
            new_name='stat_tool_num',
        ),
    ]
