# Generated by Django 3.0.1 on 2020-01-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classstatd', '0004_auto_20200104_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classstatinfo',
            name='recipe_cate',
        ),
    ]
